Draft: Feat/sher 680/add domain cms
Winzana/sherl-sdk-php pull request #12
Opened 2023-10-24 14:09 UTC by JohanAff

2023-10-30 08:39 UTC, JohanAff commented
ajouter les redirection pour person et media

2024-01-21 20:53 UTC, exiam requested changes

2024-01-21 20:53 UTC, exiam commented on docs/docs/cms-types.md
> +| BLOG     |   "blog"   | Type d'article pour un blog       |
Documentation à rédiger en anglais

2024-01-21 20:53 UTC, exiam commented on docs/docs/cms.md
> +$cmsClient->getArticleBySlug(string $slug);
Revoir l'exemple de code pour plus de clarté :

```suggestion
$sherlClient->cms->getArticleBySlug(string $slug);
```

2024-01-21 20:53 UTC, exiam commented on docs/sidebars.js
> +      "place-types",
Doublons à supprimer

2024-01-21 20:53 UTC, exiam commented on src/Cms/CmsProvider.php
> +    public function UpdateArticleById(string $id, CMSArticleUpdateInputDto $articleInput): ?ArticleDto
```suggestion
    public function updateArticleById(string $id, CMSArticleUpdateInputDto $articleInput): ?ArticleDto
```

2024-01-21 20:53 UTC, exiam commented on src/Cms/CmsProvider.php
> +            $response = $this->client->post("/api/faqs", [
Il faut revoir toutes les routes API utilisées dans le provider car celles qui sont utilisées actuellement n'existent pas côté API. Il faudrait se baser sur le SDK JS.

2024-01-21 20:53 UTC, exiam commented on src/Cms/Dto/FindPostsFiltersDto.php
> +     * @Serializer\Type("string")
Il faudrait uniformiser les types utilisés pour les propriétés de type date, et donc utilisé `DateTime` à chaque fois.

2024-01-29 14:25 UTC, david-chmarzynski commented on src/Cms/CmsProvider.php
> +                RequestOptions::QUERY => $id,
À supprimer

2024-01-29 14:25 UTC, david-chmarzynski commented on src/Cms/CmsProvider.php
> +                RequestOptions::QUERY => $id
à supprimer

2024-01-29 14:25 UTC, david-chmarzynski commented on src/Cms/CmsProvider.php
> +                RequestOptions::QUERY => $id
à supprimer

2024-01-29 14:25 UTC, david-chmarzynski commented on src/Cms/CmsProvider.php
> +                RequestOptions::QUERY => $id
à supprimer

2024-01-29 14:25 UTC, david-chmarzynski commented on src/Cms/CmsProvider.php
> +                RequestOptions::QUERY => $slug
à supprimer

2024-01-29 14:25 UTC, david-chmarzynski commented on src/Cms/CmsProvider.php
> +                RequestOptions::QUERY => $id
à supprimer

2024-01-29 14:25 UTC, david-chmarzynski commented on src/Cms/CmsProvider.php
> +                RequestOptions::QUERY => $slug
à supprimer

2024-02-15 09:23 UTC, winzana-mg commented on docs/docs/cms.md
> +This call returns a [ArticleDto](cms-types#ArticleDto) object.
```suggestion
This call returns the deleted [ArticleDto](cms-types#ArticleDto) object.
```

2024-02-15 09:25 UTC, winzana-mg commented on docs/docs/cms.md
> +$sherlClient->cms->getPosts(FindPostsFiltersDto $filter);
```suggestion
$sherlClient->cms->getPosts(FindPostsFiltersDto $filters);
```

2024-02-15 09:27 UTC, winzana-mg commented on src/Cms/Dto/CMSArticleAddMediaDto.php
> +     * @var int
```suggestion
     * @var integer
```

2024-02-15 09:27 UTC, winzana-mg commented on src/Cms/Dto/CMSArticleAddMediaDto.php
> +     * @var int
```suggestion
     * @var integer
```

2024-02-15 09:27 UTC, winzana-mg commented on src/Cms/Dto/CMSArticleCreateInputDto.php
> +     * @var \DateTime
Uniformiser en important le Datetime en haut et retiré le "/"

2024-02-15 09:28 UTC, winzana-mg commented on src/Cms/Dto/ArticleDto.php
> +     * @var \DateTime|null
Import

2024-02-15 09:28 UTC, winzana-mg commented on src/Cms/Dto/CMSArticleUpdateInputDto.php
> +     * @var \DateTime
```suggestion
     * @var DateTime
```

2024-02-15 09:28 UTC, winzana-mg commented on src/Cms/Dto/CMSArticleUpdateInputDto.php
> +     * @var \DateTime
```suggestion
     * @var DateTime
```

2024-02-15 09:28 UTC, winzana-mg commented on src/Cms/Dto/CreateCaptionOutputDto.php
> +     * @var int
```suggestion
     * @var integer
```

2024-02-15 09:28 UTC, winzana-mg commented on src/Cms/Dto/CreateThumbnailOutputDto.php
> +     * @var int
```suggestion
     * @var integer
```

2024-02-15 09:29 UTC, winzana-mg commented on src/Cms/Dto/CreateThumbnailOutputDto.php
> +     * @var int
```suggestion
     * @var integer
```

2024-02-15 09:29 UTC, winzana-mg commented on src/Cms/Dto/FindPostsFiltersDto.php
> +     * @var \DateTime
```suggestion
     * @var DateTime
```

2024-02-15 09:29 UTC, winzana-mg commented on src/Cms/Dto/FindPostsFiltersDto.php
> +     * @var \DateTime
```suggestion
     * @var DateTime
```

2024-02-15 09:30 UTC, winzana-mg commented on src/Cms/CmsProvider.php
> +                ]
```suggestion
                RequestOptions::JSON =>$data
```

2024-02-15 09:31 UTC, winzana-mg commented on src/Cms/CmsProvider.php
> + * Creates an article with the given ID and article input data.
Pas cohérent avec la fonction

2024-02-15 09:31 UTC, winzana-mg commented on src/Cms/CmsProvider.php
> +                ]
```suggestion
                RequestOptions::JSON => $articleInput
```

2024-02-15 09:31 UTC, winzana-mg commented on src/Cms/CmsProvider.php
> +                        throw $this->errorFactory->create(CmsErr::CMS_EVENT_CREATION_FAILED_FORBIDDEN);
L'erreur parle de "CREATION", mais c'est une mise à jour

2024-02-15 09:32 UTC, winzana-mg commented on src/Cms/CmsProvider.php
> +                ]
```suggestion
                RequestOptions::JSON => $faqInput
```

2024-02-15 09:33 UTC, winzana-mg commented on src/Cms/CmsProvider.php
> +                    ]
```suggestion
                RequestOptions::JSON => $data
```

2024-02-15 09:34 UTC, winzana-mg commented on src/Cms/CmsProvider.php
> +            throw $this->errorFactory->create(CmsErr::CMS_CREATE_FAILED);
Peut être trop générique

2024-02-15 09:35 UTC, winzana-mg commented on src/Cms/CmsProvider.php
> +            throw $this->errorFactory->create(CmsErr::CMS_DELETE_BY_ID_FAILED);
Aussi trop générique, ça pourrait correspondre à une stories, une page, un media etc

2024-02-15 09:36 UTC, winzana-mg commented on src/Cms/CmsProvider.php
> +    * Retrieves an article by its identifier.
Par cohérent avec la fonction

2024-02-15 09:37 UTC, winzana-mg commented on src/Cms/CmsProvider.php
> +                RequestOptions::JSON => $filters
```suggestion
                RequestOptions::QUERY => $filters
```

2024-02-15 09:38 UTC, winzana-mg commented on src/Cms/CmsProvider.php
> +                RequestOptions::JSON => $filters
```suggestion
                RequestOptions::QUERY => $filters
```

2024-02-20 17:03 UTC, merged