feat(SHER-693): add domain iam
Winzana/sherl-sdk-php pull request #13
Opened 2023-10-30 15:41 UTC by JohanAff

2023-11-06 08:48 UTC, david-chmarzynski commented on docs/docs/iam.md
> +| **roles**      | array of [RoleDto](iam-types#RoleDto) | :white_check_mark: | Array of associated roles               |
RoleDto[]

2023-11-06 08:48 UTC, david-chmarzynski commented on docs/docs/iam.md
> +| **roles**      | array of [RoleDto](iam#RoleDto) | :white_check_mark: | Array of associated roles               |
RoleDto[]

2023-11-06 08:48 UTC, david-chmarzynski commented on docs/docs/iam.md
> +| **statement**   | array of [StatementDto](iam-types#StatementDto) |        :x:         | Array of associated statements |
StatementDto[]

2023-11-06 08:48 UTC, david-chmarzynski commented on src/Iam/IamProvider.php
> +            $response = $this->client->get($this->endpoints['GET_ALL_IAM_PROFILES'], [
Mettre le bon endpoint ( $this=>endpoints n'existe pas ici )

2023-11-06 08:48 UTC, david-chmarzynski commented on src/Iam/IamProvider.php
> +                'query' => $filters
$response = $this->client->get('le/bon/endpoint', [
          "headers" => [
            "Content-Type" => "application/json",
          ],
          RequestOptions::QUERY => $filters,
        ]);

2023-11-06 08:48 UTC, david-chmarzynski commented on src/Iam/IamProvider.php
> +            $endpoint = str_replace('{id}', $id, $this->endpoints['GET_IAM_PROFILE_BY_ID']);
Supprimer str_replace pour faire comme au-dessus

2023-11-06 08:48 UTC, david-chmarzynski commented on src/Iam/IamProvider.php
> +            $endpoint = str_replace('{id}', $id, $this->endpoints['GET_IAM_ROLE_BY_ID']);
Supprimer str_replace pour mettre comme au-dessus

2024-01-21 21:02 UTC, exiam requested changes

2024-01-21 21:02 UTC, exiam commented on docs/docs/iam-types.md
> +| **createdAt**  |           datetime           |    Date and time of profile creation    |
```suggestion
| **createdAt**  |           DateTime           |    Date and time of profile creation    |
```

2024-01-21 21:02 UTC, exiam commented on docs/sidebars.js
> +      "place-types",
Doublons à supprimer

2024-01-21 21:02 UTC, exiam commented on src/Iam/IamProvider.php
> +    public function getAllIamProfiles(IamProfilesFilterDto $filters): ?ProfileDto
La route qui est appelée retourne une liste de `ProfileDto`, et non pas un seul objet.

2024-01-21 21:02 UTC, exiam commented on src/Iam/IamProvider.php
> +              RequestOptions::QUERY => $id,
Est-ce que c'est nécessaire ?

2024-01-29 14:42 UTC, david-chmarzynski commented on src/Iam/IamProvider.php
> +                    throw $this->errorFactory->create(IamErr::FETCH_FAILED);
Peut être modifier pour mettre IAM_GET_ALL_FAILED

2024-01-29 14:42 UTC, david-chmarzynski commented on src/Iam/IamProvider.php
> +            throw ErrorHelper::getSherlError($err, $this->errorFactory->create(IamErr::FETCH_FAILED));
IAM_GET_PROFILE_BY_ID_FAILED

2024-01-29 14:42 UTC, david-chmarzynski commented on src/Iam/IamProvider.php
> +            throw ErrorHelper::getSherlError($err, $this->errorFactory->create(IamErr::FETCH_FAILED));
IAM_GET_ROLE_BY_ID_FAILED

2024-02-15 09:11 UTC, winzana-mg commented on docs/docs/iam.md
> +$profiles = $sherlClient->iam->getAllIamProfiles(IamProfilesFilterDto $filter);
```suggestion
$profiles = $sherlClient->iam->getAllIamProfiles(IamProfilesFilterDto $filters);
```

2024-02-15 09:12 UTC, winzana-mg commented on docs/docs/iam.md
> +This call returns an array of [ProfileDto][]|null(Iam-types#ProfileDto).
```suggestion
This call returns an array of [ProfileDto](Iam-types#ProfileDto)[]|null.
```

2024-02-15 09:14 UTC, winzana-mg commented on docs/docs/iam.md
> +This call returns an array of [ProfileDto](Iam-types#ProfileDto).
On récupère quelque chose via un `id`. Donc je pense pas que ça peut pas te retourner un tableau.

2024-02-15 09:14 UTC, winzana-mg commented on docs/docs/iam.md
> +This call returns an RoleDto object.
Redirection vers le type

2024-02-15 09:17 UTC, winzana-mg commented on src/Iam/IamProvider.php
> +    public function getAllIamProfiles(IamProfilesFilterDto $filters): ?array
Le type de retour

2024-02-15 09:18 UTC, winzana-mg commented on src/Iam/IamProvider.php
> +            return null;
```suggestion
            if ($err instanceof \GuzzleHttp\Exception\ClientException) {
                $response = $err->getResponse();
                $statusCode = $response->getStatusCode();

                switch ($statusCode) {
                    case 403:
                        throw $this->errorFactory->create(IamErr::IAM_GET_ALL_FORBIDDEN);
                }
            }
            throw $this->errorFactory->create(IamErr::IAM_GET_ALL_FAILED);
```

2024-02-19 08:51 UTC, JohanAff commented on src/Iam/IamProvider.php
> +    public function getAllIamProfiles(IamProfilesFilterDto $filters): ?array
si je ne mais pas sa cela me genere une erreur

2024-02-19 08:53 UTC, JohanAff commented on src/Iam/IamProvider.php
> +            return null;
le return null est par rapport au type de retour cela me genere une erreur si il n'y est pas

2024-02-20 17:16 UTC, merged