feat(SHER-699): add domain quotas
Winzana/sherl-sdk-php pull request #14
Opened 2023-10-31 14:59 UTC by JohanAff

2023-11-06 08:43 UTC, david-chmarzynski commented on docs/docs/quotas-types.md
> +| **sources**       | array of QuotaSourceDto | Sources associated with the quota     |
QuotaSourceDto[]

2023-11-06 08:43 UTC, david-chmarzynski commented on docs/docs/quotas-types.md
> +| **amount**        | number                  | Amount of quota                       |
float

2023-11-06 08:43 UTC, david-chmarzynski commented on docs/docs/quotas-types.md
> +| **amount**      | number   | Amount for the quota source             |
float

2023-11-06 08:43 UTC, david-chmarzynski commented on docs/docs/quotas-types.md
> +| **remaining**   | number   | Remaining amount for the quota source   |
float

2023-11-06 08:43 UTC, david-chmarzynski commented on docs/docs/quotas.md
> +|      **id**      | integer | :white_check_mark: |  Unique identifier for the quota  |
string

2023-11-06 08:43 UTC, david-chmarzynski commented on src/Quotas/QuotasProvider.php
> +        $response = $this->client->get('/api/quotas/findOneBy', [
$response = $this->client->post("/api/quotas/findOneBy", [
          "headers" => [
            "Content-Type" => "application/json",
          ],
          RequestOptions::JSON => [
            "query" => $filters
          ]
        ]);

2024-01-21 21:12 UTC, exiam requested changes

2024-01-21 21:12 UTC, exiam commented on docs/docs/quotas-types.md
> +| **uri**           | string                | Uri for the quota                     |
```suggestion
| **uri**           | string                | URI for the quota                     |
```

2024-01-21 21:12 UTC, exiam commented on docs/docs/quotas-types.md
> +| **uri**         | string   | Uri for the quota source                |
```suggestion
| **uri**         | string   | URI for the quota source                |
```

2024-01-21 21:12 UTC, exiam commented on src/Quotas/QuotasProvider.php
> +    public function getQuotaFindOneBy(QuotaFilterDto $filters): ?QuotaOutputDto
```suggestion
    public function getQuotaFindOneBy(QuotaFilterDto $filters): ?QuotaOutputDto
```

Nommage à revoir, on pourrait notamment éviter de mettre 2 verbes (ici "get" et "find"). Par exemple "getOneQuotaBy"

2024-01-21 21:12 UTC, exiam commented on docs/docs/quotas.md
> +$quota = $sherlClient->quotas->getQuotaFindByOne(?QuotaFilterDto $filter);
Attention au nommage des méthodes dans les exemples parce que celui ci ne correspond pas à ce qui est dans le provider.

2024-01-21 21:12 UTC, exiam commented on docs/docs/quotas.md
> +title: Quotas
Revoir le nommage du domaine, côté API celui ci est nommé "Quota" (sans "s"). Il faudrait également employer le même nommage pour les dossiers, namespaces, etc.

2024-01-21 21:12 UTC, exiam commented on src/Quotas/QuotasProvider.php
> +            $response = $this->client->post("/api/quotas/findOneBy", [
Route API incorrecte. Côté API, la route est "/api/quotas/find-one-by". Et l'appel se fait en `GET`.

2024-01-21 21:12 UTC, exiam commented on src/Quotas/QuotasProvider.php
> +                RequestOptions::JSON => [
À vérifier mais j'imagine que ce serait plutôt quelque chose comme ça puisqu'il n'y a pas de propriété "filters" côté API.

```suggestion
                RequestOptions::QUERY => $filters
```

2024-01-22 08:14 UTC, JohanAff commented on docs/docs/quotas.md
> +title: Quotas
Coté js c'est quotas avec un s j'ai repris comme c'était coté api pour qu'il soit pareil donc je change ?

2024-01-29 14:48 UTC, david-chmarzynski commented on src/Quota/QuotaProvider.php
> +                    throw $this->errorFactory->create(QuotaErr::FETCH_FAILED);
Changer le nommage, peut être FETCH_QUOTA_FIND_ONE_BY_FAILED

2024-02-15 09:20 UTC, winzana-mg commented on docs/docs/quota-types.md
> +| **sources**       | QuotaSourceDto[]      | Sources associated with the quota     |
Redirection

2024-02-15 09:21 UTC, winzana-mg commented on src/Quota/Dto/QuotaFilterDto.php
> +     * @var int
```suggestion
     * @var integer
```

2024-02-15 09:21 UTC, winzana-mg commented on src/Quota/Dto/QuotaFilterDto.php
> +     * @var int
```suggestion
     * @var integer
```

2024-02-15 09:21 UTC, winzana-mg commented on src/Quota/Dto/QuotaOutputDto.php
> +     * @Serializer\Type("Sherl\Sdk\Communication\Enum\CommunicationTypeEnum")
Pourquoi avoir retiré l'ancien nommage ?

2024-02-19 08:28 UTC, winzana-mg commented on docs/docs/quota-types.md
> +|     **type**      |                  CommunicationTypeEnum                   |         Type of communication         |
la redirection

2024-02-20 17:20 UTC, merged