Draft: feat(SHER-686): implements calendar domain
Winzana/sherl-sdk-php pull request #15
Opened 2023-10-31 16:34 UTC by jg-winzana

Need to re-read.

2024-01-21 21:23 UTC, exiam requested changes

2024-01-21 21:23 UTC, exiam commented on composer.json
> +      "lint": "./vendor/bin/phpstan analyse src --level 8"
Il s'agit peut-être d'un conflit qui n'a pas été correctement réglé mais on utilise plus "src --level 8", à la place on a un fichier de configuration à la racine. Donc il faudrait annuler ce changement.

2024-01-21 21:23 UTC, exiam commented on docs/docs/calendar-enum.md
> +The king of recurence for an event
Le texte devrait être en dehors du bloc de code.

2024-01-21 21:23 UTC, exiam commented on docs/docs/calendar.md
> +| userPlaceUri |                        string                        |   :x:    | TODO                                 |
Il y a plusieurs TODO dans la documentation, sur la colonne "description", certainement à revoir.

2024-01-21 21:23 UTC, exiam commented on docs/docs/calendar.md
> +| ----------- | :-----: | :------: | ---------------------------------- | --- |
J'ai l'impression qu'il y a une colonne en trop dans ce tableau, à la fin

2024-01-21 21:23 UTC, exiam commented on src/Calendar/CalendarProvider.php
> +    public function createCalendardRequest(CreateCalendarInputDto $calendarData): ?CalendarDto
```suggestion
    public function createCalendar(CreateCalendarInputDto $calendarData): ?CalendarDto
```

Je trouve que le mot "Request" ne me parait pas nécessaire et peut aussi amener une ambiguité sur l'objectif de la route.

2024-01-21 21:23 UTC, exiam commented on src/Calendar/CalendarProvider.php
> +              RequestOptions::JSON => [
```suggestion
              RequestOptions::JSON => $calendarData
```

Est-ce qu'on pourrait passer directement l'objet ?

2024-01-21 21:23 UTC, exiam commented on src/Calendar/CalendarProvider.php
> +    public function updateCalendarRequest(string $calendarId, UpdateCalendarInputDto $calendarData): ?CalendarDto
```suggestion
    public function updateCalendar(string $calendarId, UpdateCalendarInputDto $calendarData): ?CalendarDto
```

2024-01-21 21:23 UTC, exiam commented on src/Calendar/CalendarProvider.php
> +              RequestOptions::QUERY => [
Est-ce que c'est nécessaire comme on ajoute déjà l'ID dans l'URL avec une concaténation ?

2024-01-21 21:23 UTC, exiam commented on src/Calendar/CalendarProvider.php
> +    public function createCalendarEventRequest(CreateCalendarEventInputDto $calendarData): CalendarEventDto
```suggestion
    public function createCalendarEvent(CreateCalendarEventInputDto $calendarData): CalendarEventDto
```

2024-01-21 21:23 UTC, exiam commented on src/Calendar/CalendarProvider.php
> +    public function updateCalendarEventRequest(string $calendarId, string $eventId, UpdateCalendarEventInputDto $calendarEventData): CalendarEventDto
```suggestion
    public function updateCalendarEvent(string $calendarId, string $eventId, UpdateCalendarEventInputDto $calendarEventData): CalendarEventDto
```

2024-01-21 21:23 UTC, exiam commented on src/Calendar/CalendarProvider.php
> +    public function getCalendarEventRequest(string $calendarEventId): ?CalendarEventDto
```suggestion
    public function getCalendarEvent(string $calendarEventId): ?CalendarEventDto
```

2024-01-21 21:23 UTC, exiam commented on src/Calendar/CalendarProvider.php
> +    public function getCalendarEventForCurrentPersonRequest(GetCalendarEventForCurrentPersonInputDto $input): CalendarEventsPaginatedResultDto
```suggestion
    public function getCalendarEventForCurrentPerson(GetCalendarEventForCurrentPersonInputDto $input): CalendarEventsPaginatedResultDto
```

2024-01-21 21:23 UTC, exiam commented on src/Calendar/Dto/CalendarFilterInputDto.php
> +    public $consumerId;
Le `consumerId` n'est pas nécessaire, il ne sera jamais fourni directement par le client.

2024-01-21 21:23 UTC, exiam commented on src/Calendar/Dto/CheckLocationInputDto.php
> +     * @var string
Est-ce qu'il ne manquerait pas les annotations du serializer ici ? (à moins que ce ne soit pas nécessaire)

2024-01-21 21:23 UTC, exiam commented on src/Calendar/Dto/CheckLocationOutputDto.php
> +     * @Serializer\Type("string")
Il faudrait utiliser `DateTime` pour les propriétés contenant des dates.

2024-01-22 12:27 UTC, jg-winzana commented on src/Calendar/CalendarProvider.php
> +              RequestOptions::QUERY => [
Non ce n'est pas nécessaire et surtout ça ne fait pas ce qu'on recherche ici, ça ajoute un paramètre à l'URL (écrasant ceux de l'URL si il y en avait déjà)

2024-01-22 14:25 UTC, jg-winzana commented on src/Calendar/Dto/CheckLocationInputDto.php
> +     * @var string
On avait parlé à un moment qu'on ne mettait par les serializer sur les input et c'était peut être une erreur...
Oublie dans la correction surement.

2024-01-24 12:29 UTC, jg-winzana commented on src/Calendar/CalendarProvider.php
> +              RequestOptions::JSON => [
J'ai des tests en PHP, ça à l'air d'être ok pour faire ça.

2024-02-05 15:14 UTC, jg-winzana commented
According to error found in the error management, need to rework this part.

2024-02-15 09:40 UTC, winzana-mg commented on docs/docs/calendar-enum.md
> +enum AvailabilityScale: string
Il faut mettre tout sous forme de tableau, valable pour l'ensemble du fichier

2024-02-15 09:41 UTC, winzana-mg commented on docs/docs/calendar-enum.md
> +enum AvailabilityScale: string
De plus on n'a pas besoin de séparer dans 2 fichiers différents les enums et types, à la limite à l'interieur du fichier tu peux séparer

2024-02-15 09:42 UTC, winzana-mg commented on docs/docs/calendar.md
> +| scaleValue   |                                                      |   :x:    | The number of period                 |
Manque le type

2024-02-15 09:43 UTC, winzana-mg commented on docs/docs/calendar.md
> +| **id**       | string | calendar's id                             |
```suggestion
| **id**       | string | Calendar's id                             |
```

2024-02-15 09:45 UTC, winzana-mg commented on docs/docs/calendar.md
> +$sherlClient->calendar->getAllCalendarEvents(string $eventId, GetCalendarEventForCalendarInputDto $filters );
```suggestion
$sherlClient->calendar->getAllCalendarEvents(string $calendarId, GetCalendarEventForCalendarInputDto $filters );
```

2024-02-15 09:46 UTC, winzana-mg commented on docs/docs/calendar.md
> +This call returns a [GetCalendarEventForCalendarResultsDto](calendar-types#GetCalendarEventForCalendarResultsDto) class.
```suggestion
This call returns a [GetCalendarEventForCalendarResultsDto](calendar-types#GetCalendarEventForCalendarResultsDto) objects.
```

2024-02-15 09:47 UTC, winzana-mg commented on docs/docs/calendar.md
> +This call returns a [GetCalendarEventForCalendarResultsDto](calendar-types#GetCalendarEventForCalendarResultsDto) class.
```suggestion
This call returns a [GetCalendarEventForCalendarResultsDto](calendar-types#GetCalendarEventForCalendarResultsDto) object.
```

2024-02-15 09:47 UTC, winzana-mg commented on src/Calendar/CalendarProvider.php
> +use Sherl\Sdk\Common\Error\ErrorHelper;
A supprimer

2024-02-15 09:48 UTC, winzana-mg commented on src/Calendar/CalendarProvider.php
> +            throw ErrorHelper::getSherlError(
Remplacer dans toutes les fonctions par la factory

2024-02-15 09:48 UTC, winzana-mg commented on src/Calendar/CalendarProvider.php
> +            $response = $this->client->put('/api/calendar/' . $calendarId, [
```suggestion
            $response = $this->client->put("api/calendar/$calendarId", [
```

2024-02-15 09:49 UTC, winzana-mg commented on src/Calendar/CalendarProvider.php
> +            $response = $this->client->delete('/api/calendar/' . $calendarId, [
```suggestion
            $response = $this->client->delete("/api/calendar/$calendarId", [
```

2024-02-15 09:49 UTC, winzana-mg commented on src/Calendar/CalendarProvider.php
> +            $response = $this->client->get('/api/calendar/' . $calendarId, [
```suggestion
            $response = $this->client->get("/api/calendar/$calendarId", [
```

2024-02-15 09:50 UTC, winzana-mg commented on src/Calendar/CalendarProvider.php
> +              RequestOptions::JSON => $filters
```suggestion
              RequestOptions::QUERY => $filters
```

2024-02-15 09:51 UTC, winzana-mg commented on src/Calendar/CalendarProvider.php
> +    public function checksDateAvailabilities(CheckDatesInputDto $dates): array
On a pas un retour plus précis avec un type?

2024-02-15 09:51 UTC, winzana-mg commented on src/Calendar/CalendarProvider.php
> +              RequestOptions::JSON => $dates
```suggestion
              RequestOptions::QUERY => $dates
```

2024-02-15 09:52 UTC, winzana-mg commented on src/Calendar/CalendarProvider.php
> +    public function checksDateAvailabilities(CheckDatesInputDto $dates): array
```suggestion
    public function checksDateAvailabilities(CheckDatesInputDto $dates): AvailabilityDto[]
```

2024-02-15 09:52 UTC, winzana-mg commented on src/Calendar/CalendarProvider.php
> +            $response = $this->client->get('//api/calendar/check-location', [
```suggestion
            $response = $this->client->get('/api/calendar/check-location', [
```

2024-02-15 09:52 UTC, winzana-mg commented on src/Calendar/CalendarProvider.php
> +              RequestOptions::JSON => $location
```suggestion
              RequestOptions::QUERY => $location
```

2024-02-15 09:52 UTC, winzana-mg commented on src/Calendar/CalendarProvider.php
> +              RequestOptions::JSON => $calendarFilter
```suggestion
              RequestOptions::QUERY => $calendarFilter
```

2024-02-15 09:53 UTC, winzana-mg commented on src/Calendar/CalendarProvider.php
> +            $response = $this->client->put('/api/calendar/' . $calendarId . '/event/' . $eventId, [
```suggestion
            $response = $this->client->put("/api/calendar/$calendarId/event/$eventId", [
```

2024-02-15 09:53 UTC, winzana-mg commented on src/Calendar/CalendarProvider.php
> +            $response = $this->client->delete('/api/calendar/' . $calendarId . '/event/' . $calendarEventId, [
```suggestion
            $response = $this->client->delete("/api/calendar/$calendarId/event/$calendarEventId", [
```

2024-02-15 09:54 UTC, winzana-mg commented on src/Calendar/CalendarProvider.php
> +              RequestOptions::JSON => $filters
```suggestion
              RequestOptions::QUERY => $filters
```

2024-02-15 09:54 UTC, winzana-mg commented on src/Calendar/CalendarProvider.php
> +            $response = $this->client->get('/api/calendar/' . $calendarId . '/events', [
```suggestion
            $response = $this->client->get("/api/calendar/$calendarId/events", [
```

2024-02-15 09:55 UTC, winzana-mg commented on src/Calendar/CalendarProvider.php
> +    public function getAllCalendarEvents(string $calendarId, GetCalendarEventForCalendarInputDto $filters): array
```suggestion
    public function getAllCalendarEvents(string $calendarId, GetCalendarEventForCalendarInputDto $filters): GetCalendarEventForCalendarResultsDto[]
```

Ne pas oublier de mettre l'import en haut du fichier s'il n'est pas déjà présent

2024-02-15 09:55 UTC, winzana-mg commented on src/Calendar/CalendarProvider.php
> +            $response = $this->client->put('/api/calendar-event/' . $calendarEventId, [
```suggestion
            $response = $this->client->put("/api/calendar-event/$calendarEventId", [
```

2024-02-15 09:56 UTC, winzana-mg commented on src/Calendar/CalendarProvider.php
> +            }
```suggestion
            return SerializerFactory::getInstance()->deserialize(
                $response->getBody()->getContents(),
                CalendarEventDto::class,
                'json'
            );
```

2024-02-15 09:57 UTC, winzana-mg commented on src/Calendar/CalendarProvider.php
> +              RequestOptions::JSON => $input
```suggestion
              RequestOptions::QUERY => $input
```

2024-02-15 09:58 UTC, winzana-mg commented on src/Calendar/Dto/CalendarDto.php
> +     * @var string
```suggestion
     * @var OpeningHoursSpecificationOutputDto[]
```

2024-02-15 09:58 UTC, winzana-mg commented on src/Calendar/Dto/CalendarDto.php
> +     * @var string
```suggestion
     * @var OpeningHoursSpecificationOutputDto[]
```

2024-02-15 10:00 UTC, winzana-mg commented on src/Calendar/Dto/CheckLocationOutputDto.php
> +     * @Serializer\Type("array<Sherl\Sdk\Place\Dto\GeoCoordinates>")
Je suis pas sur qu'il faut un "array", mais si oui rajouter "[]" sur le @var au dessus

2024-02-15 10:01 UTC, winzana-mg commented on src/Calendar/Dto/CreateCalendarEventInputDto.php
> +     * @Serializer\Type("string")
DateTime ?

2024-02-15 10:01 UTC, winzana-mg commented on src/Calendar/Dto/CreateCalendarEventInputDto.php
> +     * @Serializer\Type("string")
DateTime ?

2024-02-15 10:02 UTC, winzana-mg commented on src/Calendar/Dto/CreateCalendarInputDto.php
> +     * @var OpeningHoursSpecificationOutputDto
```suggestion
     * @var OpeningHoursSpecificationOutputDto[]
```

2024-02-15 10:02 UTC, winzana-mg commented on src/Calendar/Dto/FindAvailabilitiesInputDto.php
> +     * @Serializer\Type("Sherl\Sdk\Calendar\Enum\AvailabilityScale")
```suggestion
     * @Serializer\Type("enum<'Sherl\Sdk\Calendar\Enum\AvailabilityScale', 'value'>")
```

2024-02-15 10:02 UTC, winzana-mg commented on src/Calendar/Dto/FindAvailabilitiesOutputDto.php
> +     * @Serializer\Type("array<Sherl\Sdk\Place\Dto\GeoCoordinates>")
Pareil pour le "array" peut être pas utile

2024-02-15 10:03 UTC, winzana-mg commented on src/Calendar/Dto/FindAvailabilitiesOutputDto.php
> +     * @Serializer\Type("string")
DateTime ?

2024-02-15 10:03 UTC, winzana-mg commented on src/Calendar/Dto/FindAvailabilitiesOutputDto.php
> +     * @Serializer\Type("string")
DateTime ?

2024-02-15 10:03 UTC, winzana-mg commented on src/Calendar/Dto/OpeningHoursSpecificationOutputDto.php
> +     * @var string
```suggestion
     * @var string[]
```

2024-02-15 10:04 UTC, winzana-mg commented on src/Calendar/Dto/OpeningHoursSpecificationOutputDto.php
> +     * @Serializer\Type("number")
```suggestion
     * @var integer
     * @Serializer\Type("integer")
```

2024-02-15 10:04 UTC, winzana-mg commented on src/Calendar/Dto/OpeningHoursSpecificationOutputDto.php
> +     * @Serializer\Type("Sherl\Sdk\Calendar\Enum\HoursSpecificationRulesetEnum")
```suggestion
     * @Serializer\Type("enum<'Sherl\Sdk\Calendar\Enum\HoursSpecificationRulesetEnum', 'value'>")
```

2024-02-15 10:05 UTC, winzana-mg commented on src/Calendar/Dto/UpdateCalendarEventInputDto.php
> +     * @var string
```suggestion
     * @var DateFilterOutputDto
```

2024-02-15 10:05 UTC, winzana-mg commented on src/Calendar/Dto/UpdateCalendarEventInputDto.php
> +     * @var string
```suggestion
     * @var DateFilterOutputDto
```

2024-02-15 10:05 UTC, winzana-mg commented on src/Calendar/Dto/UpdateCalendarInputDto.php
> +     * @var OpeningHoursSpecificationOutputDto
```suggestion
     * @var OpeningHoursSpecificationOutputDto[]
```

2024-02-21 09:27 UTC, winzana-mg commented on docs/docs/calendar-types.md
>  | HoursSpecificationRulesetEnum | [HoursSpecificationRulesetEnum](calendar-enum#HoursSpecificationRulesetEnum) | The rules to apply to the opening hours specification       |
Faut mettre à jour les liens qui dépendaient du fichier calendar-enum

2024-02-21 09:27 UTC, winzana-mg commented on docs/docs/calendar.md
>  | scale        | [AvailabilityScale](calendar-enum#availabilityscale) |   :x:    | The kind of period                   |
même chose

2024-02-21 09:38 UTC, merged