feat(SHER-688): add domain communication
Winzana/sherl-sdk-php pull request #16
Opened 2023-11-06 09:47 UTC by david-chmarzynski

2024-01-21 21:26 UTC, exiam requested changes

2024-01-21 21:26 UTC, exiam commented on src/Communication/CommunicationProvider.php
> +    public function getCommunication(CommunicationFindByInputDto $filters): ?CommunicationOutputDto
```suggestion
    public function getCommunications(CommunicationFindByInputDto $filters): ?CommunicationOutputDto
```

La route API qui esst appelée retourne une liste, correspondant au type `ISearchResult<Communication>`.

2024-01-21 21:26 UTC, exiam commented on docs/docs/communication.md
> +| **consumerId**  |          `string`          |   :x:    | The consumer unique identifier      |
Le `consumerId` n'est pas nécessaire, on peut supprimer cette ligne.

2024-02-14 14:10 UTC, winzana-mg commented on docs/docs/communication-types.md
> +| **type**        |  `CommunicationTypeEnum`   | The communication type              |
Il manque la doc sur ces 2 énumérations

2024-02-14 14:10 UTC, winzana-mg commented on docs/docs/communication-types.md
> +| **createdAt**   |          `string`          | The communication creation date     |
C'est un DateTime plutôt

2024-02-14 14:11 UTC, winzana-mg commented on docs/docs/communication.md
> +| **type**        |  `CommunicationTypeEnum`   |   :x:    | The communication type              |
Ajouter les redirections vers les docs associées

2024-02-14 14:12 UTC, winzana-mg commented on src/Communication/CommunicationProvider.php
> +use Sherl\Sdk\Common\Error\ErrorHelper;
A supprimer

2024-02-14 14:13 UTC, winzana-mg commented on src/Communication/CommunicationProvider.php
> +            throw ErrorHelper::getSherlError($e, $this->errorFactory->create(CommunicationErr::GET_COMMUNICATION_FAILED));
à remplacer par la factory

2024-02-14 14:13 UTC, winzana-mg commented on src/Communication/Dto/CommunicationFindByInputDto.php
> +     * @Serializer\Type("Sherl\Sdk\Communication\Enum\CommunicationChannelEnum")
```suggestion
     * @Serializer\Type("enum<'Sherl\Sdk\Communication\Enum\CommunicationChannelEnum', 'value'>")
```

2024-02-14 14:13 UTC, winzana-mg commented on src/Communication/Dto/CommunicationFindByInputDto.php
> +     * @Serializer\Type("Sherl\Sdk\Communication\Enum\CommunicationTypeEnum")
```suggestion
     * @Serializer\Type("enum<'Sherl\Sdk\Communication\Enum\CommunicationTypeEnum', 'value'>")
```

2024-02-14 14:17 UTC, winzana-mg commented on src/Communication/Dto/CommunicationOutputDto.php
> +     * @Serializer\Type("Sherl\Sdk\Communication\Enum\CommunicationTypeEnum")
```suggestion
     * @Serializer\Type("enum<'Sherl\Sdk\Communication\Enum\CommunicationTypeEnum', 'value'>")
```

2024-02-14 15:40 UTC, merged