feat(SHER-698): add domain place
Winzana/sherl-sdk-php pull request #17
Opened 2023-11-06 14:21 UTC by JohanAff

2024-01-04 11:22 UTC, exiam requested changes

2024-01-05 15:06 UTC, exiam requested changes

2024-01-29 14:53 UTC, david-chmarzynski commented on docs/docs/place-types.md
> +| Property                       | Type     | Description                                                 |
Changer property par Fields

2024-01-29 14:53 UTC, david-chmarzynski commented on docs/docs/place-types.md
> +| Property      | Type   | Description                                          |
Changer Property par Fields

2024-02-14 14:02 UTC, winzana-mg commented on docs/docs/place.md
> +$places = $sherlClient->place->getPlaces(int $page, int $itemsPerPage, PlaceFindByInputDto $filters);
Les paramètres ne sont pas dans le même ordre que sur le fichier du provider

2024-02-14 14:04 UTC, winzana-mg commented on src/Place/PlaceProvider.php
> +                    "filters" => $filters,
Ici les filtres doivent être mis directement à la racine, et pas dans un noeud "filters"

2024-02-14 14:04 UTC, winzana-mg commented on src/Place/PlaceProvider.php
> +                    "itemsperpage" => $itemsPerPage
```suggestion
                    "itemsPerPage" => $itemsPerPage
```

2024-02-14 14:05 UTC, winzana-mg commented on src/Place/PlaceProvider.php
> +    throw $this->errorFactory->create(PlaceErr::FETCH_PLACES_FAILED);
ça devrait être dans le block `catch` et la c'est défini en dessous.

2024-02-14 16:25 UTC, winzana-mg commented on src/Place/PlaceProvider.php
> +                RequestOptions::JSON => $filters,
On peut pas avoir JSON dans une méthode GET.
Et voir si on peut spread le `$filters` dans le QUERY

2024-02-21 08:14 UTC, merged