feat(config): add config domain
Winzana/sherl-sdk-php pull request #18
Opened 2023-11-06 15:25 UTC by david-chmarzynski

2024-01-04 11:22 UTC, exiam requested changes

2024-01-04 11:22 UTC, exiam commented on docs/docs/config-types.md
> +| **id**        | string  | Config's id                |
Pourrait-on arriver à une description plus pertinente des champs comme pour les autres domaines ? le fait de n'indiquer que "Config's <nom du champ>" ne me semble pas apporter beaucoup de valeur.

2024-01-05 09:06 UTC, david-chmarzynski commented on src/Config/ConfigProvider.php
> +                    throw $this->errorFactory->create(ConfigErr::FETCH_FAILED);
Corriger le nom

2024-01-05 09:06 UTC, david-chmarzynski commented on src/Config/Errors/ConfigErr.php
> +    public const FETCH_FAILED = 'config/config-fetch-failed';
Corriger le nommage

2024-01-05 10:39 UTC, merged