Feat/sher 698/implement domain media
Winzana/sherl-sdk-php pull request #19
Opened 2023-11-07 10:35 UTC by JohanAff

2024-01-04 11:42 UTC, exiam requested changes

2024-01-04 11:42 UTC, exiam commented on docs/sidebars.js
> +      "user",
"user" est en doublon

2024-01-04 11:42 UTC, exiam commented on docs/sidebars.js
> +      "place-types",
"place-types" et "pagination" sont en doublon

2024-01-04 11:42 UTC, exiam commented on src/Media/Dto/UploadDataDto.php
> +use Sher\Sdk\Media\Enum\TypeEnum;
```suggestion
use Sherl\Sdk\Media\Enum\TypeEnum;
```
Il manque un "l" à Sherl dans l'import.

2024-01-04 11:42 UTC, exiam commented on src/Media/MediaProvider.php
> +        $this->errorFactory = new ErrorFactory('Media', MediaErr::$errors);
Ajouter une constante de classe nommée "DOMAIN" pour la valeur "Media".

2024-01-04 11:42 UTC, exiam commented on src/Media/MediaProvider.php
> +                    throw $this->errorFactory->create(MediaErr::GET_FILE_FAILED);
```suggestion
                    throw $this->errorFactory->create(MediaErr::UPLOAD_FILE_FAILED);
```

2024-01-05 15:40 UTC, exiam requested changes

2024-01-05 15:40 UTC, exiam commented on src/Media/MediaProvider.php
> +                        MediaQueryDto::class,
Est-ce que c'est bien `MediaQueryDto` qu'on doit utiliser ici ? cette classe a plutôt l'air de correspondre à des filtres.

Il faudrait se baser sur ce qui a été fait sur le SDK JS.

2024-01-05 15:40 UTC, exiam commented on src/Media/MediaProvider.php
> +    public function uploadFile(MediaQueryDto $data, MediaQueryDto $query): MediaQueryDto
Est-ce que c'est normal que tout soit typé `MediaQueryDto` ?

2024-01-09 10:00 UTC, Jm-Zion commented on src/Media/MediaProvider.php
> +            }
Est-ce que ce code est inatteignable comme sur javascript ?

2024-01-09 10:00 UTC, Jm-Zion commented on src/Media/MediaProvider.php
> +                case 404:
meme question

2024-01-09 10:01 UTC, Jm-Zion commented on src/Media/MediaProvider.php
> +                    throw $this->errorFactory->create(MediaErr::UPLOAD_FILE_FORBIDDEN);
meme question

2024-01-10 08:52 UTC, JohanAff commented on src/Media/MediaProvider.php
> +            }
avant de faire la gestion d'erreur comme sa nous avons tester d'avoir bien les messages d'erreur en fonction des code erreur

2024-01-10 13:44 UTC, merged