feat(person): implement person domain
Winzana/sherl-sdk-php pull request #2
Opened 2023-10-16 14:20 UTC by david-chmarzynski

2023-11-06 09:29 UTC, JohanAff commented on docs/docs/common-types.md
> +| **view**    |         | La vue de pagination (le type dépend de l'implémentation). |
il n'a pas de type ?

2023-11-06 09:31 UTC, JohanAff commented on docs/docs/person-types.md
> +| **gender**            |              `Gender`              | The gender of the person              |
le type 'gender' ?

2023-11-06 09:32 UTC, JohanAff commented on docs/docs/person-types.md
> +| **id**                  |   `int`   | The id of the Lemonway card                       |
integer

2023-11-06 09:32 UTC, JohanAff commented on docs/docs/person-types.md
> +| **transactionId**       |   `int`   | The transaction id of the Lemonway card           |
integer

2023-11-06 09:32 UTC, JohanAff commented on docs/docs/person-types.md
> +| **CreationDate**   |   `int`   | The creation date of the Mangopay card      |
integer

2023-11-06 09:32 UTC, JohanAff commented on docs/docs/person-types.md
> +| **gender**            |              `Gender`              | The gender of the person to create              |
gender?

2023-11-06 09:33 UTC, JohanAff commented on docs/docs/person-types.md
> +| **exp_month**           |   `int`   | The exp month of the stripe card           |
integer

2023-11-06 09:33 UTC, JohanAff commented on docs/docs/person-types.md
> +| **exp_year**            |   `int`   | The exp year of the stripe card            |
integer

2023-11-06 09:34 UTC, JohanAff commented on docs/docs/person.md
> +| **gender**            |              `Gender`              | :white_check_mark: | Le genre de la personne                        |
gender?

2023-11-06 09:34 UTC, JohanAff commented on docs/docs/person.md
> +| **gender**            |              `Gender`              | :white_check_mark: | Le genre de la personne                        |
gender?

2023-11-06 09:34 UTC, JohanAff commented on docs/docs/person.md
> +| **gender**            |              `Gender`              | :white_check_mark: | Le genre de la personne.             |
gender?

2023-11-06 09:35 UTC, JohanAff commented on src/Media/Dto/MediaObjectDto.php
> +     * @Serializer\Type("integer")
string

2023-11-06 09:35 UTC, JohanAff commented on src/Media/Dto/MediaObjectDto.php
> +     * @Serializer\Type("integer")
string

2023-11-06 09:36 UTC, JohanAff commented on src/Person/Dto/PersonFiltersDto.php
> +     * @var mixed
* @Serializer\Type("mixed")

2023-11-06 09:37 UTC, JohanAff commented on src/Person/Dto/PersonFiltersDto.php
> +     * @Serializer(Type("string"))
* @var Gender
     * @Serializer\Type("Sherl\Sdk\Person\Enum\Gender")

2023-11-06 09:40 UTC, JohanAff commented on src/Person/PersonProvider.php
> +        $response = $this->client->get('/api/persons/config');
try cash

2023-11-06 09:40 UTC, JohanAff commented on src/Person/PersonProvider.php
> +        $response = $this->client->get('/api/persons/me');
try cash

2023-11-06 09:40 UTC, JohanAff commented on src/Person/PersonProvider.php
> +        $response = $fetcher->get(
try cash

2023-11-06 09:40 UTC, JohanAff commented on src/Person/PersonProvider.php
> +        $response = $fetcher->get(
try cash

2023-11-06 09:54 UTC, david-chmarzynski commented on docs/docs/common-types.md
> +| **view**    |         | La vue de pagination (le type dépend de l'implémentation). |
Supprimé, présent dans pagination.md

2023-11-21 19:04 UTC, exiam requested changes

2023-11-21 19:04 UTC, exiam commented on src/Person/PersonProvider.php
> +            $response = $fetcher->get(
Les appels à l'API sont fait différemment que sur le SDK JS. En PHP on ne va pas utiliser de `$fetcher` (au passage cette ligne ne retourne-t-elle pas une erreur dans l'IDE ?) mais plutôt un client Guzzle, appelable avec `$this->client`.

```suggestion
            $response = $this->client->get(
```

À répercuter sur les autres routes qui utilisent `$fetcher`.

2023-11-21 19:04 UTC, exiam commented on src/Person/PersonProvider.php
> +                  RequestOptions::JSON => $form
Je ne pense pas que les données du fichier se passent au format JSON. Habituellement c'est plutôt du multipart/form-data. À vérifier et modifier en conséquence.

2023-11-22 13:10 UTC, david-chmarzynski commented on src/Media/Dto/ImageObjectDto.php
> +   * @Serializer\Type("Sherl\Sdk\Media\Dto\ImageObjectDto")
Erreur de nommage, rétabli sur les champs impliqués

2023-11-22 13:16 UTC, david-chmarzynski commented on src/Common/Dto/FiltersDto.php
> +class Filters
Au début je pensais qu'on allait devoir avoir une classe Filters pour étendre les autres classes de ce type ( comme PersonFiltersDto )

2023-11-22 15:24 UTC, david-chmarzynski commented on src/Person/PersonProvider.php
> +    * @return Pagination<PersonOuputDto>|null
Je suis pas sûr de comprendre avec le commentaire précédent, est-ce que tu penses à quelque chose comme ça : 

/**
 * @param type $param
 * @return ExampleOutputDto|null
 * @throws SherlException
 */

2024-01-21 20:09 UTC, exiam requested changes
Branche à mettre à jour avec develop, il y a des conflits.

2024-01-21 20:09 UTC, exiam commented on src/Person/PersonProvider.php
> +            $response = $this->client->get('/api/persons/config', [
Il faudrait vérifier que l'on ne va pas rencontrer la même erreur que pour le SDK JS, où le client Guzzle soulève lui même une exception et donc on passerait directement dans le `catch`.

À première vue ça pourrait être le cas, la documentation de Guzzle mentionne que lorsque l'on reçoit une erreur >= 400 une exception de type `ClientException` est soulevée (voir https://docs.guzzlephp.org/en/latest/quickstart.html#exceptions). Il est mentionné que ce comportement dépends de l'option "http_errors" sur le client Guzzle et visiblement cette option est à `true` par défaut. 

Il faudrait arriver à confirmer ça et ensuite envisager de déplacer le switch dans le bloc `catch`.

2024-01-21 20:09 UTC, exiam commented on src/Person/PersonProvider.php
> +            $response = $this->client->get('/api/persons/$id', [
Je ne crois pas que la variable `$id` sera correctement insérée de cette manière. Il me semble que ça fonctionne uniquement avec des guillemets double.

2024-01-21 20:09 UTC, exiam commented on src/Person/PersonProvider.php
> +                RequestOptions::QUERY => $id
On a besoin de ça si on insère nous même l'id dans l'URL ?

2024-01-21 20:09 UTC, exiam commented on src/Person/PersonProvider.php
> +                RequestOptions::QUERY => $id
Est-ce que c'est nécessaire ?

2024-01-22 10:15 UTC, david-chmarzynski commented on src/Person/Dto/PersonFiltersDto.php
> +     * @Serializer\Type("mixed")
En JS on a : location?: any;

2024-02-14 14:20 UTC, winzana-mg commented on docs/docs/person-types.md
> +| **birthDate**                |               `string`               | The birth date of the person                |
Peut être un DateTime ?

2024-02-14 14:21 UTC, winzana-mg commented on docs/docs/person-types.md
> +| **gender**                   |               `Gender`               | The gender of the person                    |
Redirection vers la doc sur le type

2024-02-14 14:21 UTC, winzana-mg commented on docs/docs/person-types.md
> +| **privacyNotive**            |    `AcceptPrivacyNoticeInputDto`     | The privacy notice status of the person     |
Redirection vers la doc

2024-02-14 15:28 UTC, winzana-mg commented on docs/docs/person-types.md
> +| **travelingGroup** | `TravelingGroup` | The traveling group type of the experience form response |
redirection

2024-02-14 15:31 UTC, winzana-mg commented on docs/docs/person-types.md
> +| **default**             | `string`  | The registered web kit token of the Lemonway card |
Je pense que le 2nd default est un copié collé oublié

2024-02-14 15:31 UTC, winzana-mg commented on docs/docs/person-types.md
> +| **cards**      | `LemonwayCardOutputDto[]` | The associated cards of the Lemonway account |
redirection

2024-02-14 15:31 UTC, winzana-mg commented on docs/docs/person-types.md
> +| **type**                       | `AccountType` | The type of the address to add                 |
redirection

2024-02-14 15:32 UTC, winzana-mg commented on docs/docs/person-types.md
> +| **address**           |         `AddressInputDto`          | The address of the person to create             |
redirection

2024-02-14 15:33 UTC, winzana-mg commented on docs/docs/person-types.md
> +| **affiliation**       | `PersonOrganizationCreateInputDto` | The affiliation of the person to create         |
redirection

2024-02-14 15:33 UTC, winzana-mg commented on docs/docs/person-types.md
> +| **sort**                      | `Sort<PersonInputDto>` | The person sorting status                          |
Redirections

2024-02-15 08:34 UTC, winzana-mg commented on docs/docs/person-types.md
> +| **sort**                      | `Sort<`[PersonInputDto](#personinputdto)`>` | The person sorting status                          |
Le `Sort` il vient d'où, ça ressemble à un type générique, est ce qu'il a déjà son morceau de doc associé ?
Si oui, mettre sa redirection, sinon le faire

2024-02-15 08:35 UTC, winzana-mg commented on docs/docs/person.md
>  | **type**                      |      `PersonType`      | :x:      | The person type to filter                          |
Ici aussi faut mettre les redirections sur tous les types/enums

2024-02-15 08:36 UTC, winzana-mg commented on src/Person/Dto/PersonFiltersDto.php
> +     * @Serializer(Type("boolean"))
Dans ce fichier plusieurs fois, une erreur de "(" à la place de "\"

2024-02-15 08:37 UTC, winzana-mg commented on src/Person/Dto/PersonFiltersDto.php
> +     * @Serializer(Type("SortDto<Sherl\Sdk\Person\Dto\PersonInputDto>"))
Ici faut voir si c'est vrai comme ça lorsqu'on a un type générique qui prend un autre type

2024-02-15 08:37 UTC, winzana-mg commented on src/Person/Dto/PersonFiltersDto.php
> +     * @Serializer(Type("Sherl\Sdk\Person\Enum\PersonType"))
```suggestion
     * @Serializer\Type("enum<'Sherl\Sdk\Person\Enum\PersonType', 'value'>")
```

2024-02-15 08:38 UTC, winzana-mg commented on src/Person/Dto/PersonInputDto.php
> +     * @Serializer\Type("Sherl\Sdk\Person\Enum\Gender")
```suggestion
     * @Serializer\Type("enum<'Sherl\Sdk\Person\Enum\Gender', 'value'>")
```

2024-02-15 08:38 UTC, winzana-mg commented on src/Person/Dto/PersonInputDto.php
> +     * @Serializer\Type("Sherl\Sdk\Person\Enum\PersonType")
```suggestion
     * @Serializer\Type("enum<'Sherl\Sdk\Person\Enum\PersonType', 'value'>")
```

2024-02-15 08:40 UTC, winzana-mg commented on src/Person/Dto/PersonUpdateAddressInputDto.php
> +     * @Serializer\Type("Sherl\Sdk\Person\Enum\AccountType")
```suggestion
     * @Serializer\Type("enum<'Sherl\Sdk\Person\Enum\AccountType', 'value'>")
```

2024-02-15 08:40 UTC, winzana-mg commented on src/Person/Dto/PersonUpdateInputDto.php
> +     * @Serializer\Type("Sherl\Sdk\Person\Enum\Gender")
```suggestion
     * @Serializer\Type("enum<'Sherl\Sdk\Person\Enum\Gender', 'value'>")
```

2024-02-15 08:41 UTC, winzana-mg commented on src/Person/Dto/PictureRegisterInputDto.php
> +     * @Serializer\Type("UploadedFileInterface")
```suggestion
     * @Serializer\Type("Psr\Http\Message\UploadedFileInterface")
```

2024-02-15 08:42 UTC, winzana-mg commented on src/Person/Dto/SessionCreationInputDto.php
> +     * @var string[] // TODO: Change type ?
Retiré le TODO, voir avec @exiam si le type est correct, sinon le modifié en conséquence

2024-02-15 08:42 UTC, winzana-mg commented on src/Person/Dto/SessionUpdateInputDto.php
> +     * @var string[] // TODO: Change type ?
Même chose

2024-02-15 08:42 UTC, winzana-mg commented on src/Person/Dto/SessionUpdateInputDto.php
> +     * @var string[] // TODO: Change type ?
Même chose

2024-02-15 08:43 UTC, winzana-mg commented on src/Person/PersonProvider.php
> +use Sherl\Sdk\Common\Error\ErrorHelper;
à supprimer

2024-02-15 08:44 UTC, winzana-mg commented on src/Person/PersonProvider.php
> +            throw ErrorHelper::getSherlError($e, $this->errorFactory->create(PersonErr::GET_CONFIGS_FAILED));
Remplacer tous les ErrorHelper par la factory

2024-02-15 08:45 UTC, winzana-mg commented on src/Person/PersonProvider.php
> +                    'filters' => $filters,
Je pense que les filters doivent être à la racine et non pas dans un noeud "filters"

2024-02-15 08:45 UTC, winzana-mg commented on src/Person/PersonProvider.php
> +                    default:
à supprimer et utiliser le throw en dehors du if

2024-02-15 08:45 UTC, winzana-mg commented on src/Person/PersonProvider.php
> +                    default:
Même chose

2024-02-19 09:33 UTC, david-chmarzynski commented on src/Person/Dto/PersonFiltersDto.php
> +     * @Serializer(Type("SortDto<Sherl\Sdk\Person\Dto\PersonInputDto>"))
SortDto a l'air d'être construit pour ça : 

`
/**
 * @template T
 */
class SortDto
`

2024-02-21 07:54 UTC, winzana-mg commented on src/Person/Dto/PersonPanelUpdateFilterInputDto.php
> +class PersonPanelUpdateFilterInputDto
Les interfaces n'ont pas étaient mise à jour dans la doc. Il faut supprimer ou modifier + dans les imports de certains fichiers, des imports ne sont plus nécessaire

2024-02-21 08:30 UTC, merged