feat(SHER-696): add domain opinion
Winzana/sherl-sdk-php pull request #21
Opened 2023-11-08 08:40 UTC by JohanAff

2023-11-10 15:28 UTC, exiam requested changes

2023-11-10 15:28 UTC, exiam commented on docs/docs/opinion-types.md
> +| Fields             |  Type   | Description                                                     |
Est-ce qu'on avait ajouté une colonne "Required" dans d'autres parties de la doc ?

2023-11-10 15:28 UTC, exiam commented on docs/docs/opinion.md
> +$opinions = $opinionClient->getOpinions(array $filters);
À quoi correspond `$opinionClient` ?

L'appel côté PHP se fait de la manière suivante : `$sherlClient->opinion->getOpinions($filters);`
On passe spécifiquement par le `$sherlClient`.

2023-11-10 15:28 UTC, exiam commented on docs/docs/opinion.md
> +filters is an associative array that should include pagination and other filter criteria.
Est-ce qu'on peut ajouter le détail de ces filtres ?

2023-11-10 15:28 UTC, exiam commented on docs/docs/opinion.md
> +data = [
```suggestion
$data = [
```

2023-11-10 15:28 UTC, exiam commented on src/Opinion/Dto/AverageDto.php
> +class OpinionUpdateStatusInputDto
Le nom de la classe ne correspond pas au nom du fichier : il faudrait mettre à jour le nom du fichier.

2023-11-10 15:28 UTC, exiam commented on src/Opinion/Dto/OpinionUpdateStatusInputDto.php
> +class AverageDto
Il semblerait que cette classe ne soit pas dans le bon fichier et qu'il y ai eu un inversement avec un autre.

2023-11-10 15:28 UTC, exiam commented on src/Opinion/OpinionProvider.php
> +class MediaProvider
```suggestion
class OpinionProvider
```

2023-11-10 15:28 UTC, exiam commented on src/Opinion/OpinionProvider.php
> +    public const DOMAIN = "Media";
```suggestion
    public const DOMAIN = "Opinion";
```

2023-11-13 07:59 UTC, JohanAff commented on docs/docs/opinion-types.md
> +| Fields             |  Type   | Description                                                     |
oui le required est dans la parti opinion.md mais pas pour les types

2024-01-04 11:38 UTC, exiam requested changes

2024-01-04 11:38 UTC, exiam commented on docs/docs/opinion.md
> +$opinions = $sherlClient->opinion->getOpinions(array $OpinionFiltersDto);
Cet appel est déjà documenté au dessus, on pourrait les regrouper en ajoutant le détail des filters au dessus.

Aussi `$OpinionFiltersDto` n'est pas de type `array` mais doit correspondre à une classe `OpinionFilterInputDto`.

2024-01-04 11:38 UTC, exiam commented on docs/docs/opinion.md
> +$opinions = $sherlClient->opinion->getOpinions(array $filters);
Cette méthode `getOpinions` est nommée `getOpinionsList`. Il faudrait conserver un seul nommage.

2024-01-04 11:38 UTC, exiam commented on docs/docs/opinion.md
> +This call returns a collection of opinions, filtered based on the provided criteria in [OpinionFiltersDto](opinion#OpinionFiltersDto).
On peut mettre un lien vers la classe `OpinionDto` qui correspond au type des résultats.

2024-01-04 11:38 UTC, exiam commented on docs/docs/opinion.md
> +$claim = $sherlClient->opinion->createOpinionClaim(string $opinionId, array $data);
`$data` ne devrait pas correspondre à un tableau ("array") mais à une classe

2024-01-04 11:38 UTC, exiam commented on docs/docs/opinion.md
> +$opinionUpdated = $sherlClient->opinion->updateOpinion(string $opinionId, array $status);
La variable "$status" ne fait pas sens ici par son nommage. Il s'agirait plutôt des données pour la mise à jour. Aussi ça ne corresponds pas à un tableau ("array") mais à une classe.

Il faut reprendre la documentation dans sa globalité pour qu'elle corresponde à ce qui est défini dans le provider.

2024-01-04 11:38 UTC, exiam commented on docs/sidebars.js
> +      "place-types",
Ces deux lignes ("pagination" et "place-types") sont en doublon

2024-01-04 11:38 UTC, exiam commented on docs/sidebars.js
> +      "user",
"user" est en doublon

2024-01-04 11:38 UTC, exiam commented on src/Opinion/Dto/AverageDto.php
> +class OpinionUpdateStatusInputDto
Pourquoi cette classe se trouve dans ce fichier ? ne devrait-elle pas avoir son propre fichier ?

2024-01-04 11:38 UTC, exiam commented on src/Opinion/Dto/AverageDto.php
> +class AverageDto
```suggestion
class OpinionAverageDto
```

De manière générale ça me paraissait bien de préfixer les Dto du nom du domaine.

2024-01-04 11:38 UTC, exiam commented on src/Opinion/Errors/OpinionErr.php
> +          'Failed to fetch opinion i give forbidden',
```suggestion
          'Failed to fetch opinion i give: Access forbidden',
```

On pourrait suivre le formalisme mis en place sur d'autres domaines pour les messages d'erreur, ça me parait être des phrases avec plus de sens.

2024-01-04 11:38 UTC, exiam commented on src/Opinion/OpinionProvider.php
> +        $this->errorFactory = new ErrorFactory('Opinion', OpinionErr::$errors);
```suggestion
        $this->errorFactory = new ErrorFactory(self::DOMAIN, OpinionErr::$errors);
```

2024-01-04 11:38 UTC, exiam commented on src/Opinion/OpinionProvider.php
> +    public function getOpinionsAverage(string $opinionToUri): ?AverageDto
Il manque la phpdoc sur les méthodes du provider

2024-01-04 14:43 UTC, JohanAff commented on docs/docs/opinion.md
> +$opinions = $sherlClient->opinion->getOpinions(array $OpinionFiltersDto);
j'ai pas compris comment tu voulais les regrouper mais j'ai regles OpinionFilterDto

2024-01-05 15:34 UTC, exiam requested changes
Il faudrait revoir les méthodes du provider + la documentation en se basant sur ce qui a été fait pour le SDK JS.

2024-01-05 15:34 UTC, exiam commented on docs/docs/opinion.md
> +$newOpinion = $sherlClient->opinion->createOpinion(array $data);
Revoir la documentation parce que la méthode ne prends pas ces arguments, il y a un id + une instance de la classe `OpinionDto`

2024-01-05 15:34 UTC, exiam commented on docs/docs/opinion.md
> +$data = [
À revoir, les données ne sont pas dans un tableau associatif mais dans une classe

2024-01-05 15:34 UTC, exiam commented on docs/docs/opinion.md
> +$opinionUpdated = $sherlClient->opinion->updateOpinion(string $id, OpinionDto $status);
Nommage de `$status` à revoir pour que ça corresponde au nommage utilisé dans le provider

2024-01-05 15:34 UTC, exiam commented on docs/docs/opinion.md
> +$status = [
Revoir le nommage de la variable + on n'utilise pas de tableau associatif mais une classe

2024-01-05 15:34 UTC, exiam commented on src/Opinion/OpinionProvider.php
> +    public function createOpinionClaim(string $id, OpinionDto $opinionData): ?OpinionDto
Les données ici ne correspondent pas à un `OpinionDto` mais à un typage particulier. En JS on utilise : 
```js
class OpinionCreateClaimInputDto {
  claimComment: string;
}
```

2024-01-05 15:34 UTC, exiam commented on src/Opinion/OpinionProvider.php
> +    public function getOpinionsIGive(OpinionDto $filtersInput): ?OpinionAverageDto
Les filtres possibles ne correspondent pas à la classe `OpinionDto` mais à cette classe
```js
class OpinionIGiveInputDto extends PageFilterDto {
  public opinionToUri?: string;
}
```

2024-01-05 15:34 UTC, exiam commented on src/Opinion/OpinionProvider.php
> +    public function getOpinionsIGive(OpinionDto $filtersInput): ?OpinionAverageDto
Les filtres possibles ne correspondent pas à la classe `OpinionDto` mais à cette classe
```js
class OpinionIGiveInputDto extends PageFilterDto {
  public opinionToUri?: string;
}
```

2024-01-29 14:57 UTC, david-chmarzynski commented on src/Opinion/Dto/OpinionDto.php
> +     * @var string
Passer en DateTime + import

2024-01-29 14:57 UTC, david-chmarzynski commented on src/Opinion/Dto/OpinionDto.php
> +     * @var string
Passer en DateTime + import

2024-01-29 14:57 UTC, david-chmarzynski commented on docs/docs/opinion-types.md
> +| **updatedAt**      | string  | Timestamp of the last update to the opinion (optional)          |
Type = datetime

2024-01-29 14:57 UTC, david-chmarzynski commented on docs/docs/opinion-types.md
> +| **createdAt**      | string  | Timestamp of when the opinion was created                       |
Type = datetime

2024-02-14 13:44 UTC, winzana-mg commented on src/Opinion/Dto/OpinionDto.php
> +    public $opinionFromUri;
Je pense que c'est censé être une string

2024-02-14 13:44 UTC, winzana-mg commented on src/Opinion/Dto/OpinionDto.php
> +    public string $createdAt;
Et ça le DateTime
```suggestion
    /**
     * @var DateTime
     * @Serializer\Type("DateTime")
     */
    public $createdAt;
```

2024-02-14 13:44 UTC, winzana-mg commented on src/Opinion/Dto/OpinionDto.php
> +    public string $uri;
```suggestion
    public $uri;
```

2024-02-14 13:45 UTC, winzana-mg commented on src/Opinion/Dto/OpinionDto.php
> +    public string $status;
```suggestion
    public $status;
```

2024-02-14 13:46 UTC, winzana-mg commented on src/Opinion/Dto/OpinionUpdateStatusInputDto.php
> +     * @Serializer\Type("Sherl\Sdk\Opinion\Dto\OpinionStatusEnum")
```suggestion
     * @Serializer\Type("enum<'Sherl\Sdk\Opinion\Dto\OpinionStatusEnum', 'value'>")
```

2024-02-14 13:47 UTC, winzana-mg commented on src/Opinion/OpinionProvider.php
> +
```suggestion
```

2024-02-14 13:49 UTC, winzana-mg commented on src/Opinion/OpinionProvider.php
> +                        throw $this->errorFactory->create(OpinionErr::CREATE_OPINION_FORBIDDEN);
C'est le même code d'erreur que la création classique de l'opinion, faudrait avoir une erreur spécifique pour la création de la claim sur l'opinion

2024-02-14 13:52 UTC, winzana-mg commented on src/Opinion/OpinionProvider.php
> +            throw $this->errorFactory->create(OpinionErr::FETCH_OPINION_AVERAGE_FAILED);
Le code d'erreur n'est pas raccord avec la fonction

2024-02-14 13:54 UTC, winzana-mg commented on src/Opinion/OpinionProvider.php
> +    public function createOpinionClaim(string $id, CreateOpinionInputDto $opinionData): ?OpinionDto
Le nom de la classe `CreateOpinionInputDto ` est pas super raccord avec le fait que c'est l'ajout d'une claim sur une opinion et pas l'input de création d'une opinion

2024-02-14 13:57 UTC, winzana-mg commented on src/Opinion/OpinionProvider.php
> + * @return OpinionDto|null - The created opinion if successful, otherwise null.
ça aussi pas super raccord, je pense.
ça retourne l'opinion mais avec la claim qu'on vient d'ajouter.

2024-02-14 14:18 UTC, JohanAff commented on src/Opinion/OpinionProvider.php
> +    public function createOpinionClaim(string $id, CreateOpinionInputDto $opinionData): ?OpinionDto
c'est le nom de la classe qui aussi en js

2024-02-14 16:00 UTC, merged