feat(SHER-700): add search domain
Winzana/sherl-sdk-php pull request #22
Opened 2023-11-08 09:17 UTC by david-chmarzynski

2023-11-10 15:20 UTC, exiam requested changes

2023-11-10 15:20 UTC, exiam commented on docs/docs/search-types.md
> +| Champs           | Type                                                                              | Description                       |
Écrire le titre des colonnes en anglais, ainsi que la description.

2024-01-03 20:38 UTC, exiam requested changes

2024-01-03 20:38 UTC, exiam commented on src/Search/Dto/SearchResultOutputDto.php
> +// use Sherl\Sdk\Organization\Dto\OrganizationOutputDto; // TODO: adjust import when Organization merged
Cet import est déjà défini au dessus, est-ce que c'est encore utile de conserver ce commentaire ?

2024-01-03 20:38 UTC, exiam commented on src/Search/Dto/SearchResultOutputDto.php
> +    public $organization;
À vérifier : est-ce que c'est bien `organization` au singulier ici même si la valeur est un tableau ?

2024-01-03 20:38 UTC, exiam commented on src/Search/Errors/SearchErr.php
> +      self::SEARCH_FORBIDDEN => 'Failed to fetch search API. Forbidden acces',
```suggestion
      self::SEARCH_FORBIDDEN => 'Failed to fetch search API. Forbidden access',
```

2024-01-04 08:04 UTC, david-chmarzynski commented on src/Search/Dto/SearchResultOutputDto.php
> +    public $organization;
Oui on a bien organization en JS également

2024-01-04 08:54 UTC, merged