Draft :Feat/sher 691/add domain Etl
Winzana/sherl-sdk-php pull request #5
Opened 2023-10-18 14:41 UTC by JohanAff

2023-11-06 09:07 UTC, david-chmarzynski commented on src/Etl/Dto/FilterOptionsModelDto.php
> +     * @Serializer\Type("number")
Ici aussi

2023-11-06 09:07 UTC, david-chmarzynski commented on src/Etl/Dto/OptionsModelDto.php
> +     * @Serializer\Type("array")
T'as pas string[] ou quelque chose dans le genre plutôt ?

2023-11-06 09:07 UTC, david-chmarzynski commented on src/Etl/Dto/OptionsModelDto.php
> +     * @var array
Ici aussi, plutôt quelque chose comme string[]

2023-11-06 09:07 UTC, david-chmarzynski commented on src/Etl/Dto/OptionsModelDto.php
> +     * @var int
integer

2023-11-06 09:07 UTC, david-chmarzynski commented on src/Etl/Dto/OptionsModelDto.php
> +     * @var bool
boolean

2023-11-06 09:07 UTC, david-chmarzynski commented on src/Etl/Dto/OptionsModelDto.php
> +     * @var bool
boolean

2023-11-06 09:07 UTC, david-chmarzynski commented on src/Etl/Dto/SchemaDestinationModelDto.php
> +     * @var bool
boolean

2023-11-06 09:07 UTC, david-chmarzynski commented on src/Etl/Dto/SchemaSourceModelDto.php
> +     * @var bool
boolean

2023-11-06 09:07 UTC, david-chmarzynski commented on src/Etl/Dto/WrapperModelDto.php
> +     * @var array
Comme toute à l'heure, peut-être plutôt quelque chose comme string[]

2023-11-06 09:07 UTC, david-chmarzynski commented on src/Etl/EtlProvider.php
> +            return json_decode($response->getBody()->getContents(), true);
return SerializerFactory::getInstance()->deserialize(
            $response->getBody()->getContents(),
            LeTypeAttendu::class,
            'json'
        );

2023-11-06 09:07 UTC, david-chmarzynski commented on src/Etl/EtlProvider.php
> +            throw new SherlException(EtlErr::EXTRACT_TRANSFORM_LOAD_FAILED, $e->getMessage());
EXTRACT_TRANSFORM_LOAD_FAILED => FETCH_FAILED

2023-11-06 09:07 UTC, david-chmarzynski commented on src/Etl/EtlProvider.php
> +            return json_decode($response->getBody()->getContents(), true);
return SerializerFactory::getInstance()->deserialize(
$response->getBody()->getContents(),
LeTypeAttendu::class,
'json'
);

2023-11-06 09:07 UTC, david-chmarzynski commented on src/Etl/EtlProvider.php
> +                RequestOptions::JSON => $config,
RequestOptions::JSON => RequestOptions::QUERY

2023-11-06 09:07 UTC, david-chmarzynski commented on src/Etl/EtlProvider.php
> +                RequestOptions::JSON => $config,
RequestOptions::JSON => RequestOptions::QUERY

2023-11-06 09:07 UTC, david-chmarzynski commented on src/Etl/EtlProvider.php
> +            return json_decode($response->getBody()->getContents(), true);
return SerializerFactory::getInstance()->deserialize(
$response->getBody()->getContents(),
LeTypeAttendu::class,
'json'
);

2023-11-06 09:07 UTC, david-chmarzynski commented on src/Etl/EtlProvider.php
> +            throw new SherlException(EtlErr::SAVE_CONFIG_FAILED, $e->getMessage());
FETCH_FAILED

2024-01-21 20:29 UTC, exiam requested changes

2024-01-21 20:29 UTC, exiam commented on docs/sidebars.js
> +      "place-types",
En doublon, "place-types" est déjà présent plus bas dans le fichier

2024-01-21 20:29 UTC, exiam commented on src/Etl/Dto/ConfigModelDto.php
> +     * @Serializer\Type("string")
Il faudrait utiliser le type `DateTime` pour les dates, plutôt que "string".

2024-01-21 20:29 UTC, exiam commented on src/Etl/Dto/DestinationModelDto.php
> +class DestinationModel
```suggestion
class DestinationModelDto
```

2024-01-21 20:29 UTC, exiam commented on src/Etl/Dto/EtlResponseDto.php
> +class EtlResponseDto
Dans le domaine "ETL" il y a plusieurs endpoints d'API. Il faudrait que le nommage de la classe reflète le nom de l'endpoint qui est utilisé, par exemple : 

```suggestion
class ExtractTransformLoadResponseDto
```

(fichier à renommer également)

2024-01-21 20:29 UTC, exiam commented on src/Etl/Dto/EtlSaveConfigInputDto.php
> +     * @Serializer\Type("Sherl\Sdk\Etl\Dto\SchemaModelDto")
Cette propriété doit être un tableau de `Sherl\Sdk\Etl\Dto\SchemaModelDto`

2024-01-21 20:29 UTC, exiam commented on src/Etl/Dto/EtlSaveConfigInputDto.php
> +     * @Serializer\Type("Sherl\Sdk\Etl\Dto\FilterModelDto")
Cette propriété doit être un tableau de `Sherl\Sdk\Etl\Dto\FilterModelDto`

2024-01-21 20:29 UTC, exiam commented on src/Etl/Dto/FilterFieldModelDto.php
> +class FilterFieldModel
```suggestion
class FilterFieldModelDto
```

Il faudrait que le nommage de la classe corresponde au nom du fichier pour que ce soit un peu plus simple de s'y retrouver.

2024-01-21 20:29 UTC, exiam commented on src/Etl/Dto/FilterModelDto.php
> +class FilterModel
```suggestion
class FilterModelDto
```

2024-01-21 20:29 UTC, exiam commented on src/Etl/Dto/FilterOptionsModelDto.php
> +class FilterOptionsModel
```suggestion
class FilterOptionsModelDto
```

2024-01-21 20:29 UTC, exiam commented on src/Etl/Dto/OptionsModelDto.php
> +class OptionsModel
```suggestion
class OptionsModelDto
```

2024-01-21 20:29 UTC, exiam commented on src/Etl/Dto/SchemaDestinationModelDto.php
> +class SchemaDestinationModel
```suggestion
class SchemaDestinationModelDto
```

2024-01-21 20:29 UTC, exiam commented on src/Etl/Dto/SchemaModelDto.php
> +class SchemaModel
```suggestion
class SchemaModelDto
```

2024-01-21 20:29 UTC, exiam commented on src/Etl/Dto/SchemaSourceModelDto.php
> +class SchemaSourceModel
```suggestion
class SchemaSourceModelDto
```

2024-01-21 20:29 UTC, exiam commented on src/Etl/Dto/SourceModelDto.php
> +class SourceModel
```suggestion
class SourceModelDto
```

2024-01-21 20:29 UTC, exiam commented on src/Etl/Dto/WrapperModelDto.php
> +class WrapperModel
```suggestion
class WrapperModelDto
```

2024-01-21 20:29 UTC, exiam commented on src/Etl/EtlProvider.php
> +
```suggestion
```

saut de ligne en trop

2024-01-21 20:29 UTC, exiam commented on src/Etl/EtlProvider.php
> +                RequestOptions::QUERY => $id
Est-ce que c'est nécessaire ?

2024-01-29 13:51 UTC, david-chmarzynski commented on src/Etl/Dto/ConfigModelDto.php
> +
Je pense que tu dois avoir une erreur d'import de DateTime

2024-01-29 13:51 UTC, david-chmarzynski commented on src/Etl/EtlProvider.php
> +            switch ($response->getStatusCode()) {
Il me semble que la changement a pas été fait au niveau du switch dans le catch

2024-01-29 13:51 UTC, david-chmarzynski commented on src/Etl/EtlProvider.php
> +            switch ($response->getStatusCode()) {
Il faut changer le switch dans le catch

2024-01-29 13:51 UTC, david-chmarzynski commented on src/Etl/EtlProvider.php
> +            switch ($response->getStatusCode()) {
Il faut passer le switch dans le catch

2024-01-29 17:53 UTC, exiam requested changes

2024-01-29 17:53 UTC, exiam commented on src/Etl/EtlProvider.php
> +            switch ($response->getStatusCode()) {
À vérifier (éventuellement voir avec @david-chmarzynski, je lui avait déjà fait ce commentaire) : il faut être sûr que l'on ai pas le même comportement que sur la partie JS ici, à savoir l'appel à la requête API au dessus qui retourne une erreur et donc on ne passe jamais dans le `switch` en dessous.

2024-01-29 17:53 UTC, exiam commented on src/Etl/EtlProvider.php
> +            $response = $this->client->post("/api/etl", [
L'URL est invalide, on devrait utiliser : 
```suggestion
            $response = $this->client->post("/api/etl/extract-transform-load", [
```

2024-01-29 17:53 UTC, exiam commented on src/Etl/EtlProvider.php
> +            $response = $this->client->post("/api/save-config", [
URL incorrecte, il manque le préfixe de l'ETL : 
```suggestion
            $response = $this->client->post("/api/etl/save-config", [
```

2024-02-15 08:49 UTC, winzana-mg commented on src/Etl/Dto/DestinationModelDto.php
> +     * @Serializer\Type("Sherl\Sdk\Etl\Dto\LoaderTypeEnum")
```suggestion
     * @Serializer\Type("enum<'Sherl\Sdk\Etl\Dto\LoaderTypeEnum', 'value'>")
```

2024-02-15 08:49 UTC, winzana-mg commented on src/Etl/Dto/DestinationModelDto.php
> +     * @Serializer\Type("Sherl\Sdk\Etl\Dto\DatabaseLoaderTypeEnum")
```suggestion
     * @Serializer\Type("enum<'Sherl\Sdk\Etl\Dto\DatabaseLoaderTypeEnum', 'value'>")
```

2024-02-15 08:50 UTC, winzana-mg commented on src/Etl/Dto/OptionsModelDto.php
> +     * @Serializer\Type("Sherl\Sdk\Etl\Enum\HttpRequestTypeEnum")
```suggestion
     * @Serializer\Type("enum<'Sherl\Sdk\Etl\Enum\HttpRequestTypeEnum', 'value'>")
```

2024-02-15 08:50 UTC, winzana-mg commented on src/Etl/Dto/OptionsModelDto.php
> +     * @Serializer\Type("Sherl\Sdk\Etl\Enum\MimeTypeEnum")
```suggestion
     * @Serializer\Type("enum<'Sherl\Sdk\Etl\Enum\MimeTypeEnum', 'value'>")
```

2024-02-15 08:51 UTC, winzana-mg commented on src/Etl/Dto/SchemaDestinationModelDto.php
> +     * @Serializer\Type("Sherl\Sdk\Etl\Enum\FieldValueTypesEnum")
```suggestion
     * @Serializer\Type("enum<'Sherl\Sdk\Etl\Enum\FieldValueTypesEnum', 'value'>")
```

2024-02-15 08:51 UTC, winzana-mg commented on src/Etl/Dto/SchemaDestinationModelDto.php
> +     * @Serializer\Type("Sherl\Sdk\Etl\Enum\FieldValueTypesEnum")
```suggestion
     * @Serializer\Type("enum<'Sherl\Sdk\Etl\Enum\FieldValueTypesEnum', 'value'>")
```

2024-02-15 08:51 UTC, winzana-mg commented on src/Etl/Dto/SchemaSourceModelDto.php
> +     * @Serializer\Type("Sherl\Sdk\Etl\Enum\FieldValueTypesEnum")
```suggestion
     * @Serializer\Type("enum<'Sherl\Sdk\Etl\Enum\FieldValueTypesEnum', 'value'>")
```

2024-02-15 08:51 UTC, winzana-mg commented on src/Etl/Dto/SchemaSourceModelDto.php
> +     * @Serializer\Type("Sherl\Sdk\Etl\Enum\FieldValueTypesEnum")
```suggestion
     * @Serializer\Type("enum<'Sherl\Sdk\Etl\Enum\FieldValueTypesEnum', 'value'>")
```

2024-02-15 08:52 UTC, winzana-mg commented on src/Etl/Dto/SourceModelDto.php
> +     * @Serializer\Type("Sherl\Sdk\Etl\Enum\ExtractSourceMethodEnum")
```suggestion
     * @Serializer\Type("enum<'Sherl\Sdk\Etl\Enum\ExtractSourceMethodEnum', 'value'>")
```

2024-02-15 08:52 UTC, winzana-mg commented on src/Etl/Dto/WrapperModelDto.php
> +     * @Serializer\Type("Sherl\Sdk\Etl\Enum\WrapperIdentifierEnum")
```suggestion
     * @Serializer\Type("enum<'Sherl\Sdk\Etl\Enum\WrapperIdentifierEnum', 'value'>")
```

2024-02-15 08:52 UTC, winzana-mg commented on src/Etl/Dto/WrapperModelDto.php
> +     * @Serializer\Type("object")
Faut pas plutôt mettre "mixed" ?

2024-02-15 08:55 UTC, winzana-mg commented on docs/docs/etl-types.md
> +| source      |   SourceModelDto    | Source information.                            |
Ajouter les redirections pour chaque interface/enums

2024-02-20 16:53 UTC, merged